![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

#1
my_array=np.arange(10)

#2
print(my_array[9:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [7]:
my_array=np.arange(10)
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [ ]:
my_array=np.arange(10)
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [ ]:
#1
matriz=np.arange(1,21).reshape(4,5)
print(matriz,"\n")

#2
print(np.flip(matriz))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [ ]:
np.array([matriz[0][0:2],matriz[1][0:2]])

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [67]:
matriz=np.arange(1,21).reshape(4,5)
np.array([matriz[0][::2],matriz[2][::2]])

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [70]:
matriz=np.arange(1,21).reshape(4,5)
np.array([matriz[0][::-1],matriz[1][::-1],matriz[2][::-1]])

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [76]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [78]:
print(x[x=="Loro"])

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [ ]:
array=np.arange(1,21)
array1,array2=np.split(array,2)
print(np.array([array1.reshape((5,2)),array2.reshape((5,2))]))

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [ ]:
matriz=np.arange(1,21).reshape(4,5)
print(matriz)
np.flip(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [ ]:
array=np.zeros(10,dtype=int)
print(array)

print(array.nbytes)

array[3]=1
print(array)

[0 0 0 0 0 0 0 0 0 0]
80
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [ ]:
array=np.arange(10,50)
print(array)

print(np.flip(array))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [ ]:
vector=np.array([1,2,0,0,4,0])
print(np.nonzero(vector)) #para sacar los indices de los valores

[1 2 0 0 4 0]
[1 2 4]
(array([0, 1, 4]),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [29]:
matriz=np.random.randint(1,1001,size=(10,10))
print(matriz)
print(np.max(matriz))
print(np.min(matriz))

[[643 311 430  24  32 252 400  41 640 397]
 [ 11 427 309 469 702 999 985 582  33 740]
 [347 340 724 263 836 327  40 161 273 895]
 [899 430 199 498 831 645 894 734 342 702]
 [185 761 432 252 959 661 190 293 289 238]
 [734  99 833 276 277 401 259 900 432 429]
 [897 477  45 360  31 597 661 180  26 473]
 [226 286 417 334 497 816 110 588 760 134]
 [338  24 518 675 625 750 334 352 174 813]
 [ 79 768 128 472 389 935  26 115 727 177]]
999
11


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [34]:
vector=np.random.randint(30,size=(30))
print(vector)

np.mean(vector)

[18  4  6 19 26 12 18  0 20 18 14 17 27 10  5  1 27 27 24  8  1 21 17 10
 27 22 11  1  1 22]


np.float64(14.466666666666667)

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [ ]:
array=np.zeros((10,10),dtype=int)
print(array,"\n")

#array[filas,columnas] -> 2d
array[0]=1
array[-1]=1
array[:,0]=1  #dame todas las filas de la columna 0
array[:,-1]=1

print(array)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] 

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
matriz=np.zeros((8,8),dtype=int)
print(matriz,"\n")

#en las filas impares meteme un 1 en las columnas pares
#en las filas pares meteme un 1 en las columnas impares

matriz[1::2,0::2]=1
matriz[0::2,1::2]=1

print(matriz)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]] 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [102]:
matriz=np.zeros((8,8),dtype=int)
print(matriz,"\n")

cola1=np.array([0,1])
cola2=np.array([1,0])
matriz[0::2]=np.tile(cola1,(1,4))
matriz[1::2]=np.tile(cola2,(1,4))

print(matriz)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]] 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [108]:
matriz=np.random.randint(1,101,size=(5,5))
print(matriz)

print(np.mean(matriz))
print(np.std(matriz))

(matriz[::]-np.mean(matriz))/np.std(matriz)

[[91 44 63 47 16]
 [23 91 38  6 52]
 [14 39 68 92 61]
 [17 67 16 34 38]
 [23 66 30 35 64]]
45.4
24.80483823773096


array([[ 1.83835103, -0.0564406 ,  0.709539  ,  0.06450355, -1.18525264],
       [-0.90304963,  1.83835103, -0.2983289 , -1.5883998 ,  0.26607712],
       [-1.26588207, -0.25801418,  0.91111257,  1.87866575,  0.62890956],
       [-1.14493792,  0.87079786, -1.18525264, -0.45958776, -0.2983289 ],
       [-0.90304963,  0.83048314, -0.62084662, -0.41927304,  0.74985371]])

## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
#1
array=np.arange(1,11)
print(array)

#2
array[(array==3)|(array==8)]=-1
print(array)

#3
array[(array>3)&(array<8)]*=-1
print(array)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2 -1  4  5  6  7 -1  9 10]
[ 1  2 -1 -4 -5 -6 -7 -1  9 10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [353]:
import random

#1
tablero=np.full((10,10)," ")

# def crea_tablero(lado):
#     tablero = np.full((lado,lado)," ")
#     return tablero
# crea_tablero(10)


#2
# tablero[0:2,1:2]="O" #barco eslora 2
# tablero[1:2,3:7]="O" #barco eslora 4
# print(tablero,"\n")

barco1 = [(0,1),(1,1)]
barco2 = [(1,3), (1,4), (1,5), (1,6)]
def coloca_barco(tablero, barco):
    for i in barco:
        tablero[i] = "O"
    return tablero

tablero = coloca_barco(tablero, barco1)
tablero = coloca_barco(tablero, barco2)
print(tablero)


#3
# x=int(input("Introduce la coordenada x del barco que quieres derribar:"))
# y=int(input("Introduce la coordenada y del barco que quieres derribar:"))
# tablero[x,y]="O"
# print(tablero,"\n")

# def recibir_disparo(tablero, coordenada):
#     if tablero[coordenada]=="O":
#         tablero[coordenada]="X"
#         print("Tocado")
#     elif tablero[coordenada]=="X":
#         print("Ese barco ya ha sido golpeado en ese sitio")
#     else:
#         tablero[coordenada]="-"
#         print("Agua")

# recibir_disparo(tablero,(x,y))
# print(tablero)


#4
# x=int(input("Introduce la coordenada x del barco que quieres derribar:"))
# y=int(input("Introduce la coordenada y del barco que quieres derribar:"))
# tablero[x,y]="-"
# print(tablero)



#5
def coloca_barco_plus(tablero, barco):
    # Nos devuelve el tablero si puede colocar el barco, si no devuelve False, y avise por pantalla
    tablero_temp = tablero.copy()
    num_max_filas = tablero.shape[0]
    num_max_columnas = tablero.shape[1]
    for pieza in barco:
        fila = pieza[0]
        columna = pieza[1]
        if fila < 0  or fila >= num_max_filas:
            print(f"No puedo poner la pieza {pieza} porque se sale del tablero")
            return False
        if columna <0 or columna>= num_max_columnas:
            print(f"No puedo poner la pieza {pieza} porque se sale del tablero")
            return False
        if tablero[pieza] == "O" or tablero[pieza] == "X":
            print(f"No puedo poner la pieza {pieza} porque hay otro barco")
            return False
        tablero_temp[pieza] = "O"
    return tablero_temp



def crea_barco_aleatorio(tablero,eslora = 4, num_intentos = 100):
    num_max_filas = tablero.shape[0]
    num_max_columnas = tablero.shape[1]
    while True:
        barco = []
        # Construimos el hipotetico barco
        pieza_original = (random.randint(0,num_max_filas-1),random.randint(0, num_max_columnas -1))
        print("Pieza original:", pieza_original)
        barco.append(pieza_original)
        orientacion = random.choice(["N","S","O","E"])
        print("Con orientacion", orientacion)
        fila = pieza_original[0]
        columna = pieza_original[1]
        for i in range(eslora -1):
            if orientacion == "N":
                fila -= 1
            elif orientacion  == "S":
                fila += 1
            elif orientacion == "E":
                columna += 1
            else:
                columna -= 1
            pieza = (fila,columna)
            barco.append(pieza)
        tablero_temp = coloca_barco_plus(tablero, barco)
        if type(tablero_temp) == np.ndarray:
            return tablero_temp
        print("Tengo que intentar colocar otro barco")


tablero = crea_barco_aleatorio(tablero)
print(tablero)




# posicion_buena=True
# orientacion_buena=True
# orientacion=random.choice(["N","S","E","O"])
# #orientacion=random.choice(["N"])
# posicion_inicial=np.array([random.randint(0,9),random.randint(0,9)])

# while posicion_buena==True:
#     if tablero[posicion_inicial[0],posicion_inicial[1]]=="-" or tablero[posicion_inicial[0],posicion_inicial[1]]=="O":
#         print("posicion",posicion_inicial,"ocupada")
#         posicion_inicial=np.array([random.randint(0,9),random.randint(0,9)])
#     posicion_buena=False

# print(posicion_inicial)


# while orientacion_buena==True:
#     if orientacion=="N" and (posicion_inicial[0]-4)<0:
#         print("no cabe en la matriz")
#         orientacion=random.choice(["N","S","E","O"])
#         posicion_inicial=np.array([random.randint(0,9),random.randint(0,9)])
#     elif orientacion=="S" and (posicion_inicial[0]+4)>9:
#         print("no cabe en la matriz")
#         orientacion=random.choice(["N","S","E","O"])
#         posicion_inicial=np.array([random.randint(0,9),random.randint(0,9)])
#     elif orientacion=="E" and (posicion_inicial[1]+4)>9:
#         print("no cabe en la matriz")
#         orientacion=random.choice(["N","S","E","O"])
#         posicion_inicial=np.array([random.randint(0,9),random.randint(0,9)])
#     elif orientacion=="O" and (posicion_inicial[1]-4)<0:
#         print("no cabe en la matriz")
#         orientacion=random.choice(["N","S","E","O"])
#         posicion_inicial=np.array([random.randint(0,9),random.randint(0,9)])
#     else:
#         orientacion_buena=False

# #Coloca el barco según la orientación
# for i in range(4):
#     if orientacion=="N":
#         tablero[posicion_inicial[0]-i,posicion_inicial[1]]="O"
#     elif orientacion=="S":
#         tablero[posicion_inicial[0]+i,posicion_inicial[1]]="O"
#     elif orientacion=="E":
#         tablero[posicion_inicial[0],posicion_inicial[1]+i]="O"
#     else:
#         tablero[posicion_inicial[0],posicion_inicial[1]-i]="O"

# print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
Pieza original: (1, 3)
Con orientacion E
No puedo poner la pieza (1, 3) porque hay otro barco
Tengo que intentar colocar otro barco
Pieza original: (5, 9)
Con orientacion S
[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'O']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'O']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'O']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'O']
 [' ' ' '